### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by j-t-s** [j-t-s/COSC625-Software-Engineering-Project#1]
The proposal for group project will be due September 5. Only one member of group needs to submit. The proposal should be 1 or 2 paragraphs with as much detail as possible. Examples of projects are website(4 - 5 pages), game, napster, etc).

**Comment by j-t-s** [comment]
See #8

**Comment by wrkealey** [comment]
Sorry. Not super familiar with GIT and prioritized expedience.
