### ISSUE TITLE
Procedural design

### ISSUE THREAD

**Issue by j-t-s** [j-t-s/COSC625-Software-Engineering-Project#30]
a. module descriptions

**Module Name:**
Abstract:
Implementation:
Exports:
Imports:
Pre Conditions:
Post Conditions:
Input:
Output:
Subparts:
Error Handling:
Side Effects:
Miscellany:

**Comment by j-t-s** [comment]
- [ ] App
Modules to work on:
- [ ] LoginModal
- [ ] LoginUtil
- [ ] Home
- [ ] RuleGuidelines
- [ ] Account
- [ ] UpsertPost
- [ ] View Post
- [ ] Library
- [ ] ProfileImage
- [ ] PostList

**Comment by wrkealey** [comment]
Login Modal should be double checked. I think I got parameters and things right but I very easily could be misreading how the code works.

**Comment by wrkealey** [comment]
Ditto for LoginUtil

**Comment by j-t-s** [comment]
Login Modal and LoginUtil look good to me

**Comment by j-t-s** [comment]
I worked on PostList and ProfileImage. Let me know how it looks.

**Comment by j-t-s** [comment]
The modules are written.
They just need reviewed.

**Comment by wrkealey** [comment]
I'll take a closer look in the morning. I've been studying for an exam on Thursday and looking at technical charts right now will make my eyes fall out.

Thanks again Joe.
