### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by j-t-s** [j-t-s/COSC625-Software-Engineering-Project#36]
We need to do a presentation of the project.
>  Each group will submit during Finals week slides(including notes) that would represent 
a presentation of the final project for the group

@erikus6 @wrkealey

**Comment by wrkealey** [comment]
We do. I mentioned in my last email from a few days ago that I want to start that tonight or tomorrow. I'll add it to the repo to share it. But it makes sense for me to do the intro and then pass it off to both of you to add on to.

**Comment by j-t-s** [comment]
We made the group presetnation
